---
- name: Prepare
  hosts: all
  gather_facts: True
  tasks: []

- name: Solr-standalone
  hosts: all
  roles:
    - role: lean_delivery.java
    - role: ansible-role-solr-standalone
  vars:
    solr_change_default_password: False
